// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Системные и временные метрики ---
	BootCounter uint32 `protobuf:"varint,1,opt,name=boot_counter,json=bootCounter,proto3" json:"boot_counter,omitempty"` // Счетчик перезагрузок устройства
	TimeStart   uint64 `protobuf:"varint,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`       // Время старта устройства (Unix Timestamp, секунды)
	TimeSend    uint64 `protobuf:"varint,3,opt,name=time_send,json=timeSend,proto3" json:"time_send,omitempty"`          // Время отправки данных (Unix Timestamp, секунды)
	// --- Данные с основных сенсоров ---
	TemperatureBme280 float32 `protobuf:"fixed32,4,opt,name=temperature_bme280,json=temperatureBme280,proto3" json:"temperature_bme280,omitempty"` // Температура, датчик 1
	Humidity          float32 `protobuf:"fixed32,5,opt,name=humidity,proto3" json:"humidity,omitempty"`                                            // Влажность (humidity)
	Pressure          float32 `protobuf:"fixed32,6,opt,name=pressure,proto3" json:"pressure,omitempty"`                                            // Давление (pressure)
	TemperatureRtc    float32 `protobuf:"fixed32,7,opt,name=temperature_rtc,json=temperatureRtc,proto3" json:"temperature_rtc,omitempty"`          // Температура, датчик 2
	WaterTemperature  float32 `protobuf:"fixed32,8,opt,name=water_temperature,json=waterTemperature,proto3" json:"water_temperature,omitempty"`    // Температура воды
	WaterLevel        float32 `protobuf:"fixed32,9,opt,name=water_level,json=waterLevel,proto3" json:"water_level,omitempty"`                      // Глубина
	UBattery          float32 `protobuf:"fixed32,10,opt,name=u_battery,json=uBattery,proto3" json:"u_battery,omitempty"`                           // Напряжение АКБ
	LoadCurrent       float32 `protobuf:"fixed32,11,opt,name=load_current,json=loadCurrent,proto3" json:"load_current,omitempty"`                  // Ток
	LoadPower         float32 `protobuf:"fixed32,12,opt,name=load_power,json=loadPower,proto3" json:"load_power,omitempty"`                        // Мощность
	// --- Идентификационная информация (метаданные) ---
	DevId     uint64  `protobuf:"varint,13,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`             // ID устройства
	GpsY      float32 `protobuf:"fixed32,14,opt,name=gps_y,json=gpsY,proto3" json:"gps_y,omitempty"`               // Координаты "широта"
	GpsX      float32 `protobuf:"fixed32,15,opt,name=gps_x,json=gpsX,proto3" json:"gps_x,omitempty"`               // Координаты "долгота"
	TimeMount uint64  `protobuf:"varint,16,opt,name=time_mount,json=timeMount,proto3" json:"time_mount,omitempty"` // Дата установки
	Ver       string  `protobuf:"bytes,17,opt,name=ver,proto3" json:"ver,omitempty"`                               // Версия прошивки
	// --- Данные о связи и питании ---
	Quality       int32   `protobuf:"varint,18,opt,name=quality,proto3" json:"quality,omitempty"`                               // Качество сигнала (может быть отрицательным, поэтому int32)
	OperatorName  string  `protobuf:"bytes,19,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`  // Название оператора связи
	Bat           uint32  `protobuf:"varint,20,opt,name=bat,proto3" json:"bat,omitempty"`                                       // Уровень заряда батареи в %
	UModem        float32 `protobuf:"fixed32,21,opt,name=u_modem,json=uModem,proto3" json:"u_modem,omitempty"`                  // Напряжение на модеме
	Imei          string  `protobuf:"bytes,22,opt,name=imei,proto3" json:"imei,omitempty"`                                      // IMEI модема
	OperatorTime  uint64  `protobuf:"varint,23,opt,name=operator_time,json=operatorTime,proto3" json:"operator_time,omitempty"` // Время, полученное от оператора (Unix Timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryData) GetBootCounter() uint32 {
	if x != nil {
		return x.BootCounter
	}
	return 0
}

func (x *TelemetryData) GetTimeStart() uint64 {
	if x != nil {
		return x.TimeStart
	}
	return 0
}

func (x *TelemetryData) GetTimeSend() uint64 {
	if x != nil {
		return x.TimeSend
	}
	return 0
}

func (x *TelemetryData) GetTemperatureBme280() float32 {
	if x != nil {
		return x.TemperatureBme280
	}
	return 0
}

func (x *TelemetryData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *TelemetryData) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *TelemetryData) GetTemperatureRtc() float32 {
	if x != nil {
		return x.TemperatureRtc
	}
	return 0
}

func (x *TelemetryData) GetWaterTemperature() float32 {
	if x != nil {
		return x.WaterTemperature
	}
	return 0
}

func (x *TelemetryData) GetWaterLevel() float32 {
	if x != nil {
		return x.WaterLevel
	}
	return 0
}

func (x *TelemetryData) GetUBattery() float32 {
	if x != nil {
		return x.UBattery
	}
	return 0
}

func (x *TelemetryData) GetLoadCurrent() float32 {
	if x != nil {
		return x.LoadCurrent
	}
	return 0
}

func (x *TelemetryData) GetLoadPower() float32 {
	if x != nil {
		return x.LoadPower
	}
	return 0
}

func (x *TelemetryData) GetDevId() uint64 {
	if x != nil {
		return x.DevId
	}
	return 0
}

func (x *TelemetryData) GetGpsY() float32 {
	if x != nil {
		return x.GpsY
	}
	return 0
}

func (x *TelemetryData) GetGpsX() float32 {
	if x != nil {
		return x.GpsX
	}
	return 0
}

func (x *TelemetryData) GetTimeMount() uint64 {
	if x != nil {
		return x.TimeMount
	}
	return 0
}

func (x *TelemetryData) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *TelemetryData) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *TelemetryData) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *TelemetryData) GetBat() uint32 {
	if x != nil {
		return x.Bat
	}
	return 0
}

func (x *TelemetryData) GetUModem() float32 {
	if x != nil {
		return x.UModem
	}
	return 0
}

func (x *TelemetryData) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *TelemetryData) GetOperatorTime() uint64 {
	if x != nil {
		return x.OperatorTime
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\riot.telemetry\"\xc0\x05\n" +
	"\rTelemetryData\x12!\n" +
	"\fboot_counter\x18\x01 \x01(\rR\vbootCounter\x12\x1d\n" +
	"\n" +
	"time_start\x18\x02 \x01(\x04R\ttimeStart\x12\x1b\n" +
	"\ttime_send\x18\x03 \x01(\x04R\btimeSend\x12-\n" +
	"\x12temperature_bme280\x18\x04 \x01(\x02R\x11temperatureBme280\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\x02R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\x06 \x01(\x02R\bpressure\x12'\n" +
	"\x0ftemperature_rtc\x18\a \x01(\x02R\x0etemperatureRtc\x12+\n" +
	"\x11water_temperature\x18\b \x01(\x02R\x10waterTemperature\x12\x1f\n" +
	"\vwater_level\x18\t \x01(\x02R\n" +
	"waterLevel\x12\x1b\n" +
	"\tu_battery\x18\n" +
	" \x01(\x02R\buBattery\x12!\n" +
	"\fload_current\x18\v \x01(\x02R\vloadCurrent\x12\x1d\n" +
	"\n" +
	"load_power\x18\f \x01(\x02R\tloadPower\x12\x15\n" +
	"\x06dev_id\x18\r \x01(\x04R\x05devId\x12\x13\n" +
	"\x05gps_y\x18\x0e \x01(\x02R\x04gpsY\x12\x13\n" +
	"\x05gps_x\x18\x0f \x01(\x02R\x04gpsX\x12\x1d\n" +
	"\n" +
	"time_mount\x18\x10 \x01(\x04R\ttimeMount\x12\x10\n" +
	"\x03ver\x18\x11 \x01(\tR\x03ver\x12\x18\n" +
	"\aquality\x18\x12 \x01(\x05R\aquality\x12#\n" +
	"\roperator_name\x18\x13 \x01(\tR\foperatorName\x12\x10\n" +
	"\x03bat\x18\x14 \x01(\rR\x03bat\x12\x17\n" +
	"\au_modem\x18\x15 \x01(\x02R\x06uModem\x12\x12\n" +
	"\x04imei\x18\x16 \x01(\tR\x04imei\x12#\n" +
	"\roperator_time\x18\x17 \x01(\x04R\foperatorTimeB\rZ\v./telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_telemetry_proto_goTypes = []any{
	(*TelemetryData)(nil), // 0: iot.telemetry.TelemetryData
}
var file_telemetry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
