/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_IOT_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_IOT_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _iot_telemetry_TelemetryData {
    /* --- Системные и временные метрики --- */
    uint32_t boot_counter; /* Счетчик перезагрузок устройства */
    uint64_t time_start; /* Время старта устройства (Unix Timestamp, секунды) */
    uint64_t time_send; /* Время отправки данных (Unix Timestamp, секунды) */
    /* --- Данные с основных сенсоров --- */
    float temperature_bme280; /* Температура, датчик 1 */
    float humidity; /* Влажность (humidity) */
    float pressure; /* Давление (pressure) */
    float temperature_rtc; /* Температура, датчик 2 */
    float water_temperature; /* Температура воды */
    float water_level; /* Глубина */
    float u_battery; /* Напряжение АКБ */
    float load_current; /* Ток */
    float load_power; /* Мощность */
    /* --- Идентификационная информация (метаданные) --- */
    uint64_t dev_id; /* ID устройства */
    float gps_y; /* Координаты "широта" */
    float gps_x; /* Координаты "долгота" */
    uint64_t time_mount; /* Дата установки */
    char ver[32]; /* Версия прошивки */
    /* --- Данные о связи и питании --- */
    int32_t quality; /* Качество сигнала (может быть отрицательным, поэтому int32) */
    char operator_name[32]; /* Название оператора связи */
    uint32_t bat; /* Уровень заряда батареи в % */
    float u_modem; /* Напряжение на модеме */
    char imei[32]; /* IMEI модема */
    uint64_t operator_time; /* Время, полученное от оператора (Unix Timestamp) */
} iot_telemetry_TelemetryData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define iot_telemetry_TelemetryData_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, "", 0, 0, "", 0}
#define iot_telemetry_TelemetryData_init_zero    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, "", 0, 0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define iot_telemetry_TelemetryData_boot_counter_tag 1
#define iot_telemetry_TelemetryData_time_start_tag 2
#define iot_telemetry_TelemetryData_time_send_tag 3
#define iot_telemetry_TelemetryData_temperature_bme280_tag 4
#define iot_telemetry_TelemetryData_humidity_tag 5
#define iot_telemetry_TelemetryData_pressure_tag 6
#define iot_telemetry_TelemetryData_temperature_rtc_tag 7
#define iot_telemetry_TelemetryData_water_temperature_tag 8
#define iot_telemetry_TelemetryData_water_level_tag 9
#define iot_telemetry_TelemetryData_u_battery_tag 10
#define iot_telemetry_TelemetryData_load_current_tag 11
#define iot_telemetry_TelemetryData_load_power_tag 12
#define iot_telemetry_TelemetryData_dev_id_tag   13
#define iot_telemetry_TelemetryData_gps_y_tag    14
#define iot_telemetry_TelemetryData_gps_x_tag    15
#define iot_telemetry_TelemetryData_time_mount_tag 16
#define iot_telemetry_TelemetryData_ver_tag      17
#define iot_telemetry_TelemetryData_quality_tag  18
#define iot_telemetry_TelemetryData_operator_name_tag 19
#define iot_telemetry_TelemetryData_bat_tag      20
#define iot_telemetry_TelemetryData_u_modem_tag  21
#define iot_telemetry_TelemetryData_imei_tag     22
#define iot_telemetry_TelemetryData_operator_time_tag 23

/* Struct field encoding specification for nanopb */
#define iot_telemetry_TelemetryData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   boot_counter,      1) \
X(a, STATIC,   SINGULAR, UINT64,   time_start,        2) \
X(a, STATIC,   SINGULAR, UINT64,   time_send,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_bme280,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_rtc,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    water_temperature,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    water_level,       9) \
X(a, STATIC,   SINGULAR, FLOAT,    u_battery,        10) \
X(a, STATIC,   SINGULAR, FLOAT,    load_current,     11) \
X(a, STATIC,   SINGULAR, FLOAT,    load_power,       12) \
X(a, STATIC,   SINGULAR, UINT64,   dev_id,           13) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_y,            14) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_x,            15) \
X(a, STATIC,   SINGULAR, UINT64,   time_mount,       16) \
X(a, STATIC,   SINGULAR, STRING,   ver,              17) \
X(a, STATIC,   SINGULAR, INT32,    quality,          18) \
X(a, STATIC,   SINGULAR, STRING,   operator_name,    19) \
X(a, STATIC,   SINGULAR, UINT32,   bat,              20) \
X(a, STATIC,   SINGULAR, FLOAT,    u_modem,          21) \
X(a, STATIC,   SINGULAR, STRING,   imei,             22) \
X(a, STATIC,   SINGULAR, UINT64,   operator_time,    23)
#define iot_telemetry_TelemetryData_CALLBACK NULL
#define iot_telemetry_TelemetryData_DEFAULT NULL

extern const pb_msgdesc_t iot_telemetry_TelemetryData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iot_telemetry_TelemetryData_fields &iot_telemetry_TelemetryData_msg

/* Maximum encoded size of messages (where known) */
#define IOT_TELEMETRY_TELEMETRY_PB_H_MAX_SIZE    iot_telemetry_TelemetryData_size
#define iot_telemetry_TelemetryData_size         245

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
